apiVersion: batch/v1
kind: CronJob
metadata:
  name: dd-cron-dns
  namespace: default
  labels:
    app: dd-cron-dns
    managed-by: underpost
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dd-cron-dns
            managed-by: underpost
        spec:
          containers:
            - name: dd-cron-dns
              image: underpost/underpost-engine:v3.0.1
              command:
                - /bin/sh
                - -c
                - >
                   cd /home/dd/engine && node bin env dd-cron production && node bin cron --git --dev --ssh dd-cron dns
              volumeMounts:
                - mountPath: /home/dd/engine
                  name: underpost-cron-container-volume
                - mountPath: /usr/lib/node_modules/underpost/.env
                  name: underpost-share-env
                  subPath: .env
          volumes:
            - hostPath:
                path: /home/dd/engine
                type: Directory
              name: underpost-cron-container-volume
            - hostPath:
                path: /root/.nvm/versions/node/v24.10.0/lib/node_modules/underpost
                type: DirectoryOrCreate
              name: underpost-share-env
          restartPolicy: OnFailure
