apiVersion: batch/v1
kind: CronJob
metadata:
  name: dd-cron-dns
  namespace: default
  labels:
    app: dd-cron-dns
    managed-by: underpost
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dd-cron-dns
            managed-by: underpost
        spec:
          containers:
            - name: dd-cron-dns
              image: underpost/underpost-engine:v2.99.6
              command:
                - /bin/sh
                - -c
                - >
                  cd /home/dd/engine && node bin run secret && node bin env dd-cron production && node bin cron --git --dev dd-cron dns
              volumeMounts:
                - mountPath: /home/dd/engine
                  name: underpost-cron-container-volume
          volumes:
            - hostPath:
                path: /home/dd/engine
                type: Directory
              name: underpost-cron-container-volume
          restartPolicy: OnFailure
