
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: underpost.net
spec:
  virtualhost:
    fqdn: underpost.net
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4013
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4014
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.underpost.net
spec:
  virtualhost:
    fqdn: www.underpost.net
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4015
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: cryptokoyn.net
spec:
  virtualhost:
    fqdn: cryptokoyn.net
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4016
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4017
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.cryptokoyn.net
spec:
  virtualhost:
    fqdn: www.cryptokoyn.net
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4018
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dogmadual.com
spec:
  virtualhost:
    fqdn: dogmadual.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4019
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.dogmadual.com
spec:
  virtualhost:
    fqdn: www.dogmadual.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4020
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4021
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nexodev.org
spec:
  virtualhost:
    fqdn: nexodev.org
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4022
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.nexodev.org
spec:
  virtualhost:
    fqdn: www.nexodev.org
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4023
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4024
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: healthcare.nexodev.org
spec:
  virtualhost:
    fqdn: healthcare.nexodev.org
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4025
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4026
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: itemledger.com
spec:
  virtualhost:
    fqdn: itemledger.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4027
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4028
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.itemledger.com
spec:
  virtualhost:
    fqdn: www.itemledger.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4029
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.bymyelectrics.com
spec:
  virtualhost:
    fqdn: www.bymyelectrics.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4030
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4031
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: bymyelectrics.com
spec:
  virtualhost:
    fqdn: bymyelectrics.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4032
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vitaintegral.nexodev.org
spec:
  virtualhost:
    fqdn: vitaintegral.nexodev.org
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4033
          weight: 100
    
    - conditions:
        - prefix: /peer
      enableWebsockets: true
      services:
        - name: dd-core-development-blue-service
          port: 4034
          weight: 100
    