---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-blue
  labels:
    app: dd-test-development-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-blue
  template:
    metadata:
      labels:
        app: dd-test-development-blue
    spec:
      containers:
        - name: dd-test-development-blue
          image: localhost/rockylinux9-underpost:v2.89.2
#          resources:
#            requests:
#              memory: "96294Ki"
#              cpu: "75m"
#            limits:
#              memory: "1540709Ki"
#              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 &&
              npm install -g underpost &&
              underpost secret underpost --create-from-file /etc/config/.env.development &&
              underpost start --build --run dd-test development
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: underpost-config
---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-blue-service
spec:
  selector:
    app: dd-test-development-blue
  ports:
    - name: 'tcp-4030'
      protocol: TCP
      port: 4030
      targetPort: 4030
    - name: 'udp-4030'
      protocol: UDP
      port: 4030
      targetPort: 4030

    - name: 'tcp-4031'
      protocol: TCP
      port: 4031
      targetPort: 4031
    - name: 'udp-4031'
      protocol: UDP
      port: 4031
      targetPort: 4031

    - name: 'tcp-4032'
      protocol: TCP
      port: 4032
      targetPort: 4032
    - name: 'udp-4032'
      protocol: UDP
      port: 4032
      targetPort: 4032

    - name: 'tcp-4033'
      protocol: TCP
      port: 4033
      targetPort: 4033
    - name: 'udp-4033'
      protocol: UDP
      port: 4033
      targetPort: 4033
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-green
  labels:
    app: dd-test-development-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-green
  template:
    metadata:
      labels:
        app: dd-test-development-green
    spec:
      containers:
        - name: dd-test-development-green
          image: localhost/rockylinux9-underpost:v2.89.2
#          resources:
#            requests:
#              memory: "96294Ki"
#              cpu: "75m"
#            limits:
#              memory: "1540709Ki"
#              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 &&
              npm install -g underpost &&
              underpost secret underpost --create-from-file /etc/config/.env.development &&
              underpost start --build --run dd-test development
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: underpost-config
---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-green-service
spec:
  selector:
    app: dd-test-development-green
  ports:
    - name: 'tcp-4030'
      protocol: TCP
      port: 4030
      targetPort: 4030
    - name: 'udp-4030'
      protocol: UDP
      port: 4030
      targetPort: 4030

    - name: 'tcp-4031'
      protocol: TCP
      port: 4031
      targetPort: 4031
    - name: 'udp-4031'
      protocol: UDP
      port: 4031
      targetPort: 4031

    - name: 'tcp-4032'
      protocol: TCP
      port: 4032
      targetPort: 4032
    - name: 'udp-4032'
      protocol: UDP
      port: 4032
      targetPort: 4032

    - name: 'tcp-4033'
      protocol: TCP
      port: 4033
      targetPort: 4033
    - name: 'udp-4033'
      protocol: UDP
      port: 4033
      targetPort: 4033
  type: LoadBalancer
