apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: default
  labels:
    group: db
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - port: 8079
      targetPort: 8080
