apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster
  labels:
    app: ipfs-cluster
spec:
  clusterIP: None
  selector:
    app: ipfs-cluster
  ports:
    - name: swarm
      port: 4001
      protocol: TCP
    - name: swarm-udp
      port: 4001
      protocol: UDP
    - name: api
      port: 5001
      protocol: TCP
    - name: ws
      port: 8081
      protocol: TCP
    - name: http
      port: 8080
      protocol: TCP
    - name: api-http
      port: 9094
      protocol: TCP
    - name: proxy-http
      port: 9095
      protocol: TCP
    - name: cluster-swarm
      port: 9096
      protocol: TCP
