apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ipfs-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
