name: CI | Engine cyberia | github repository
on:
  workflow_run:
    workflows: ['CI | Publish npm repository package']
    types:
      - completed
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  pwa-microservices-template:
    name: Update github repo package Jobs
    env:
      SYNC: ${{ startsWith(github.event.workflow_run.head_commit.message, 'ci(package-pwa-microservices-template-sync-engine-cyberia)') }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/rockylinux/rockylinux:9
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install required packages
        run: |
          dnf install -y sudo tar gzip bzip2 git
          dnf install -y curl --allowerasing

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_24.x | bash -
          dnf install nodejs -y

      - name: Install dependencies
        run: |
          npm install -g underpost
          npm install
          underpost config set GITHUB_TOKEN ${{ secrets.GIT_AUTH_TOKEN }}

      - name: Set git global credentials
        run: |
          git config --global user.name 'underpostnet'
          git config --global user.email 'development@underpost.net'

      - name: Build repository
        run: |
          cd .. && underpost clone underpostnet/pwa-microservices-template
          FULL_MSG=$(cd pwa-microservices-template && git log -1 --pretty=%B 2>/dev/null || echo "")
          LAST_COMMIT_MESSAGE=$(echo "$FULL_MSG" | sed 's/^[^)]*) *//')
          if [ -z "$LAST_COMMIT_MESSAGE" ]; then
            LAST_COMMIT_MESSAGE="Update engine cyberia repository"
          fi
          echo "[INFO] Captured commit message: $LAST_COMMIT_MESSAGE"
          underpost clone --bare underpostnet/engine-cyberia
          cd engine
          node bin/build dd-cyberia development
          cd ../pwa-microservices-template
          rm -rf ./.git
          mv ../engine-cyberia.git ./.git
          git init
          git config user.name 'underpostnet'
          git config user.email 'development@underpost.net'
          git add .
          git commit -m "$LAST_COMMIT_MESSAGE"
          underpost push . underpostnet/engine-cyberia
          if [ "${SYNC}" = "true" ]; then
            echo "[INFO] Init engine-cyberia deployment"
            underpost config set GITHUB_USERNAME underpostnet
            mkdir -p /home/dd
            sudo rm -rf /home/dd/engine
            cd /home/dd
            underpost clone underpostnet/engine
            cd engine
            npm install
            node bin run ssh-deploy sync-engine-cyberia
          else
            echo "[INFO] Deployment skipped"
          fi
